version: '2'
services:
  pgadmin:
    container_name: pgadmin_dev
    image: dpage/pgadmin4:3.4
    environment:
      PGADMIN_DEFAULT_EMAIL: "email@email.com"
      PGADMIN_DEFAULT_PASSWORD: pwd
    ports:
     - "80:80"
    volumes:
     - "~/pgadmin:/var/lib/pgadmin"
